### ISSUE TITLE
Example/Basic Crash on iOS when navigating back to play page

### ISSUE THREAD

**Issue by Citylogic** [fuse-compound/Fuse.StreamingPlayer#4]
The app crashes when navigating back to the play page.  We are having this issue on an app we want to release, and are experiencing the same issue on the Basic example.

Pressing the 'Stop' button in the example app returns to the artists page. From here selecting an artist crashes the app.  Audio does not need to be playing for the app to crash.

Version 7.1 & 6.9 Mac High Sierra

```
2018-02-23 11:31:10.587758+0200 StreamingBasics[2852:1038505] Error: Uno.Exception: Unexpected Uno.Exception ---> Uno.Exception: Dictionary already contains the given key
   at Uno.Collections.Dictionary`2.Add(TKey,TValue)
   at StreamingPlayer.Playlist.SetPlaylist(Uno.Collections.List<StreamingPlayer.Track>,int)
   at StreamingPlayer.StreamingPlayer.SetPlaylist(Uno.Collections.List<StreamingPlayer.Track>)
   at StreamingPlayer.StreamingPlayerModule.SetPlaylist(Fuse.Scripting.Array)
   at Fuse.Scripting.NativeProperty`2.SetProperty(Fuse.Scripting.Context,object[])
   at Fuse.Scripting.JavaScriptCore.Context.CallbackWrapper.Call(Fuse.Scripting.JavaScriptCore.JSValueRef[],Fuse.Scripting.JavaScriptCore.JSValueRef&)
   at Fuse.Scripting.JavaScriptCore.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()
    --- End of inner exception stack trace ---
   at Fuse.Scripting.JavaScriptCore.Context.ThrowPendingException()
   at Fuse.Scripting.JavaScriptCore.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()
```

**Comment by cbaggers** [comment]
Seems like we have a bug in Fuse.MediaQuery as we are getting `null` back for the `path` info in the track. Very odd

**Comment by cbaggers** [comment]
The issue was that iOS' `MPMediaQuery` will return tracks which are not on the device but are instead in iCloud
This means the path is nil and the player freaks out. Please pull the latest code from this library and also from Fuse.MediaQuery

**Comment by cbaggers** [comment]
Feel free to reopen if the issue persists. It's not occurring on the devices I have access to
